name: Shop Homepage CD
on: [push]
env: 
  CYPRESS_CACHE_FOLDER: cypress/cache
defaults:
  run:
    working-directory: src/shop
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
    - name: Setup Node
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: Cache Node Modules
      id: cache-node-modules
      uses: actions/cache@v2
      with:
        path: src/shop/node_modules
        key: node-modules-${{ hashFiles('src/shop/package-lock.json') }}
    - name: Cache Cypress Binary
      id: cache-cypress-binary
      uses: actions/cache@v2
      with:
        path: src/shop/cypress/cache
        key: cypress-binary-${{ hashFiles('src/shop/package-lock.json') }}
    - name: Install Dependencies
      if: steps.cache.outputs.cache-hit != 'true'
      run: npm install
    - name: Run Tests
      run: npm test