name: Shop Homepage Continuous Delivery Pipeline
on:
  push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/cache@v2
      with:
        path: '**/node_modules'
        key: ${{ hashFiles('**/package.lock') }}
    - uses: actions/setup-node@v1
      with:
        node-version: 10
    - run: npm install
    - run: npm test
